### ISSUE TITLE
Form elements

### ISSUE THREAD

**Issue by ahmadalfy** [kalamoni/kalamoni.github.io#3]
I know we didn't talk about forms yet but I will love to talk about it here till we explain that in the course.

You can use `<input type="email" />` instead of `<input type="text" />` ... That will force the browser to evaluate the string and return error to the user if he didn't submit an email. Plain out of the box without libraries ...

Also you are using `<input type="submit" />`. It would be better to use the element `button` cause this way you can simply style the input in CSS using the selector `.form input` without worring that the same selector will also select the submit button :)

Keep up the great work

**Comment by kalamoni** [comment]
:+1:
